### ISSUE TITLE
bind popup not action

### ISSUE THREAD

**Issue by songfaqi** [Esri/esri-leaflet-heatmap#18]
the following code not action
```
featureLayer.bindPopup(function (evt) {
    return L.Util.template('<p><b>{name}</b><br>Address：{address}</p>', evt.feature.properties);
});
```

**Comment by jgravois** [comment]
`bindPopup()` is a method inherited from [L.Layer](http://leafletjs.com/reference-1.0.0.html#layer-bindpopup) (typically something like a [Marker](http://leafletjs.com/reference-1.0.0.html#marker), [Polyline](http://leafletjs.com/reference-1.0.0.html#polyline), [Polygon](http://leafletjs.com/reference-1.0.0.html#polygon) or [Circle](http://leafletjs.com/reference-1.0.0.html#circle)).

esri-leaflet-heatmap substitutes a raster heatmap aggregation drawn on the canvas for the actual features in the service.  because unique vector features aren't being drawn, you can't bind/display popups.
